const criteria=[
{id:'US01-AC01',us:'US01',story:'Authentification',text:'Un utilisateur valide peut se connecter.',p:1,n:0,e:0,test:'TC-US01-AC01-01 connexion standard valide',file:'tests/us01-authentication/ac01-login.spec.js',proof:'Action : login(standard_user). Assertion : URL /inventory.html et titre Products visible.',rec:'Ajouter un cas de session expirée ou de réponse d’authentification indisponible.'},
{id:'US01-AC02',us:'US01',story:'Authentification',text:'Un utilisateur bloqué ne peut pas accéder à l’application.',p:0,n:1,e:0,test:'TC-US01-AC02-02 utilisateur bloqué',file:'tests/us01-authentication/ac01-login.spec.js',proof:'Action : login(locked_out_user). Assertion : message contenant “locked out”.',rec:'Ajouter une vérification d’absence de session et d’impossibilité d’accès direct au catalogue.'},
{id:'US01-AC03',us:'US01',story:'Authentification',text:'Des identifiants invalides provoquent un message d’erreur.',p:0,n:1,e:0,test:'TC-US01-AC02-01 / 03 / 04 / 05',file:'tests/us01-authentication/ac01-login.spec.js',proof:'Actions : mauvais mot de passe ou champs absents. Assertions : messages Username/Password required ou mismatch.',rec:'Tester la fermeture du message et une erreur technique distincte du refus métier.'},
{id:'US02-AC01',us:'US02',story:'Catalogue',text:'Les produits sont affichés après authentification.',p:1,n:0,e:0,test:'TC-US02-AC01-01 / 02 / 05',file:'tests/us02-catalogue/ac01-catalogue.spec.js',proof:'Assertions : 6 articles ; nom, description, prix et bouton Add to cart pour chacun.',rec:'Ajouter catalogue vide, données produit incomplètes et accès sans authentification.'},
{id:'US02-AC02',us:'US02',story:'Catalogue',text:'Le tri modifie correctement l’ordre d’affichage.',p:1,n:0,e:0,test:'TC-US02-AC02-01 à 05',file:'tests/us02-catalogue/ac01-catalogue.spec.js',proof:'Actions : quatre critères de tri. Assertions : listes exactes de noms et prix.',rec:'Vérifier conservation du nombre/contenu et réaction à une valeur de tri invalide.'},
{id:'US02-AC03',us:'US02',story:'Catalogue',text:'Les informations d’un produit sont accessibles.',p:1,n:0,e:0,test:'TC-US02-AC01-03/04',file:'tests/us02-catalogue/ac01-catalogue.spec.js',proof:'Action : ouvrir Backpack. Assertions : URL détail, nom, prix, puis retour catalogue.',rec:'Tester produit introuvable, données manquantes et ajout depuis la fiche.'},
{id:'US03-AC01',us:'US03',story:'Gestion du panier',text:'Un produit peut être ajouté au panier.',p:1,n:0,e:0,test:'TC-US03-AC01-01 / 02',file:'tests/us03-panier/ac01-panier.spec.js',proof:'Actions : ajout d’un puis trois produits. Assertions : badge 1/3 et bouton Remove.',rec:'Tester double ajout, erreur d’état et ajout depuis la fiche produit.'},
{id:'US03-AC02',us:'US03',story:'Gestion du panier',text:'Un produit peut être retiré du panier.',p:1,n:0,e:0,test:'TC-US03-AC01-03 / 04 / 05',file:'tests/us03-panier/ac01-panier.spec.js',proof:'Retrait catalogue/panier. Assertions : badge absent ou à 2, contenu exact restant.',rec:'Tester retrait d’un article absent et échec de synchronisation du panier.'},
{id:'US03-AC03',us:'US03',story:'Gestion du panier',text:'Le contenu du panier est affiché.',p:1,n:0,e:0,test:'TC-US03-AC02-01 / 02 / 03',file:'tests/us03-panier/ac01-panier.spec.js',proof:'Assertions : panier vide, quantités, noms exacts et conservation pendant navigation.',rec:'Tester données incohérentes, prix/quantités erronés et état indisponible.'},
{id:'US03-AC04',us:'US03',story:'Gestion du panier',text:'L’utilisateur peut revenir au catalogue.',p:1,n:0,e:0,test:'TC-US03-AC02-04',file:'tests/us03-panier/ac01-panier.spec.js',proof:'Action : Continue Shopping. Assertions : URL inventory.html et titre visible.',rec:'Tester retour avec panier rempli et erreur de navigation.'},
{id:'US04-AC01',us:'US04',story:'Checkout',text:'Les informations client sont obligatoires.',p:1,n:1,e:0,test:'TC-US04-AC01-01 à 05 + AC02-01',file:'tests/us04-checkout/ac01-informations.spec.js',proof:'Cas invalides par champ et tous vides ; correction après erreur ; données nominales acceptées.',rec:'Ajouter limites de longueur, espaces seuls, caractères spéciaux et panne technique.'},
{id:'US04-AC02',us:'US04',story:'Checkout',text:'Le récapitulatif de commande est affiché.',p:1,n:0,e:0,test:'TC-US05-AC01-01/03/04 et AC01-02',file:'tests/us05-e2e/ac01-commande.spec.js',proof:'Assertions : produits, quantités, sous-total, taxe et total cohérents.',rec:'Tester panier vide, montant incohérent et données produit indisponibles.'},
{id:'US04-AC03',us:'US04',story:'Checkout',text:'La commande peut être validée.',p:1,n:0,e:0,test:'TC-US05-AC02-01 / 02',file:'tests/us05-e2e/ac01-commande.spec.js',proof:'Actions : checkout d’un et trois produits jusqu’à Finish. Confirmation atteinte.',rec:'Tester double clic, panier vide et erreur lors de la finalisation.'},
{id:'US04-AC04',us:'US04',story:'Checkout',text:'Une confirmation est affichée.',p:1,n:0,e:0,test:'TC-US05-AC02-03/04/05',file:'tests/us05-e2e/ac01-commande.spec.js',proof:'Assertions : message de confirmation, retour produits et panier réinitialisé.',rec:'Tester confirmation absente/incomplète et rafraîchissement de la page.'},
{id:'US05-AC01',us:'US05',story:'Parcours complet',text:'Le parcours complet peut être réalisé sans erreur.',p:1,n:0,e:0,test:'TC-US05-AC02-01 / 02',file:'tests/us05-e2e/ac01-commande.spec.js',proof:'Parcours complet avec un puis trois articles jusqu’à la confirmation.',rec:'Ajouter un parcours interrompu avec reprise et un incident technique contrôlé.'},
{id:'US05-AC02',us:'US05',story:'Parcours complet',text:'La commande est confirmée avec succès.',p:1,n:0,e:0,test:'TC-US05-AC02-03/04/05',file:'tests/us05-e2e/ac01-commande.spec.js',proof:'Confirmation vérifiée, retour catalogue et badge panier absent.',rec:'Tester échec de confirmation, rejeu et cohérence après rafraîchissement.'}
];
const stories={US01:['Authentification',3],US02:['Catalogue',3],US03:['Gestion du panier',4],US04:['Checkout',4],US05:['Parcours complet',2]};
const label=(ok,type,name)=>`<span class="case ${ok?'':'missing'}"><i class="${type}"></i>${name} ${ok?'✓':'—'}</span>`;
function render(){const us=storyFilter.value,type=caseFilter.value,q=search.value.toLowerCase();const filtered=criteria.filter(c=>(us==='all'||c.us===us)&&(type==='all'||type==='pass'&&c.p||type==='fail'&&c.n||type==='error'&&c.e||type==='incomplete'&&!(c.p&&c.n&&c.e))&&(c.text+' '+c.id+' '+c.story).toLowerCase().includes(q));document.querySelector('#criteria').innerHTML=filtered.map(c=>`<article class="criterion"><div class="criterion-head" tabindex="0" role="button" aria-expanded="false"><span class="criterion-id">${c.id}</span><div class="criterion-title"><strong>${c.text}</strong><small>${c.us} · ${c.story}</small></div><div class="cases">${label(c.p,'pass','PASSANT')}${label(c.n,'fail','NON PASSANT')}${label(c.e,'error','ERREUR')}</div><span class="expand">+</span></div><div class="evidence"><div class="proof"><h4>PREUVE AUTOMATISÉE</h4><p><code>${c.test}</code></p><p><code>${c.file}</code></p><p>${c.proof}</p></div><div class="recommend"><h4>COUVERTURE À AJOUTER</h4><p>${c.rec}</p></div></div></article>`).join('');empty.hidden=filtered.length>0;document.querySelectorAll('.criterion-head').forEach(h=>{const toggle=()=>{const row=h.parentElement;row.classList.toggle('open');h.setAttribute('aria-expanded',row.classList.contains('open'))};h.onclick=toggle;h.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle()}}})}
[storyFilter,caseFilter,search].forEach(x=>x.addEventListener('input',render));render();
storyCards.innerHTML=Object.entries(stories).map(([id,[name,total]])=>{const rows=criteria.filter(c=>c.us===id),p=rows.filter(c=>c.p).length,n=rows.filter(c=>c.n).length,e=rows.filter(c=>c.e).length;return `<article class="story-card"><span>${id}</span><h3>${name}</h3><p>${total} critères d’acceptation analysés</p><div class="story-bars"><div><span>PASSANT</span><i style="--w:${p/total*100}%;--color:var(--lime)"></i><b>${p}/${total}</b></div><div><span>NON PASS.</span><i style="--w:${n/total*100}%;--color:var(--orange)"></i><b>${n}/${total}</b></div><div><span>ERREUR</span><i style="--w:${e/total*100}%;--color:var(--pink)"></i><b>${e}/${total}</b></div></div></article>`}).join('');
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('show');io.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll('.reveal,.metric').forEach(x=>io.observe(x));theme.onclick=()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark'};
